# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7bab12333da4c16f1849f40f00b99dc80e2b5e6b35ad355b16d29b8775ad6d2abd92d1c506d6e9911451f996963af43c76ae9add8cdc3db7c2e380786ba821d

test:
  secret_key_base: 4ad81403061da079e81e958ea378b24302e70554199624062e74efc3f8cea987ee467e64473a63a9a3c8060edfaeb49e46c622c34a73fdaf0d47fb5091a028dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
